sonar.projectKey=BiotrackProject_biotrack-api
sonar.organization=biotrackproject

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

sonar.exclusions=src/server.ts,src/config/swagger.ts,src/config/env.ts,src/config/database.ts,src/config/auth0.ts,src/middleware/authenticate.ts,src/middleware/auditLog.ts,src/shared/utils/email.ts,src/shared/utils/trackingCode.ts,src/modules/auth/auth.service.ts,src/modules/auth/auth.controller.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
